name: Update Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y miller
          pip install yq

      - name: Run update script
        run: |
          bash script/update_feed.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/timeline.jsonl
          if ! git diff --staged --quiet; then
            git commit -m "Update feed timeline"
            git push
          else
            echo "No changes to commit"
          fi
